// templates/kit-vue/src/prototypes/example/Detail.vue
<!--
  src/prototypes/example/Detail.vue  →  Route /p/example/detail

  Second screen in the same prototype. The file name is lowercased for the
  route; another screen would simply be another file alongside it.

  Parameters are passed through the query string (?id=…), which also works in
  the single-file export after the hash: #/p/example/detail?id=A-2481
-->

<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink, useRoute } from 'vue-router'

import { DsButton } from '../../components'
import { auftragById, statusFarbe } from './_shared/data'
import Shell from './_shared/Shell.vue'

const route = useRoute()
const id = computed(() => {
  const value = route.query.id
  return typeof value === 'string' ? value : null
})
const auftrag = computed(() => auftragById(id.value))
const zurueck = { to: '/p/example', label: 'Work orders' }
</script>

<template>
  <Shell v-if="!auftrag" titel="Work order" :zurueck="zurueck">
    <p class="text-base text-ink">This work order does not exist.</p>
    <p class="mt-3 text-sm text-ink-muted">
      Empty state: considered explicitly, not omitted.
    </p>
    <RouterLink to="/p/example" class="mt-6 inline-block">
      <DsButton variant="secondary">Back to list</DsButton>
    </RouterLink>
  </Shell>

  <Shell v-else :titel="auftrag.titel" :zurueck="zurueck">
    <div class="flex flex-wrap items-center gap-4">
      <span class="font-mono text-sm text-ink-muted">{{ auftrag.id }}</span>
      <span
        class="rounded-full px-3 py-1 text-xs font-medium"
        :class="statusFarbe[auftrag.status]"
      >
        {{ auftrag.status }}
      </span>
    </div>

    <dl class="mt-6 grid gap-4 sm:grid-cols-2">
      <div>
        <dt class="text-xs text-ink-muted">Customer</dt>
        <dd class="mt-1 text-base text-ink">{{ auftrag.kunde }}</dd>
      </div>
      <div>
        <dt class="text-xs text-ink-muted">Service location</dt>
        <dd class="mt-1 text-base text-ink">{{ auftrag.ort }}</dd>
      </div>
      <div>
        <dt class="text-xs text-ink-muted">Due</dt>
        <dd class="mt-1 text-base text-ink">{{ auftrag.faellig }}</dd>
      </div>
    </dl>

    <p class="mt-6 max-w-2xl text-base text-ink">{{ auftrag.beschreibung }}</p>

    <h2 class="mt-8 text-lg font-medium text-ink">Line items</h2>
    <ul class="mt-4 divide-y divide-line rounded-lg border border-line">
      <li
        v-for="position in auftrag.positionen"
        :key="position.bezeichnung"
        class="flex justify-between gap-4 p-4"
      >
        <span class="text-base text-ink">{{ position.bezeichnung }}</span>
        <span class="font-mono text-sm text-ink-muted">{{ position.menge }}×</span>
      </li>
    </ul>

    <div class="mt-8 flex flex-wrap gap-3">
      <DsButton>Complete</DsButton>
      <DsButton variant="secondary">Reschedule</DsButton>
      <DsButton variant="ghost" size="sm">View service report</DsButton>
    </div>
  </Shell>
</template>

// templates/kit-react/src/prototypes/example/Detail.tsx
/*
 * src/prototypes/example/Detail.tsx  →  Route /p/example/detail
 *
 * Second screen in the same prototype. The file name is lowercased for the
 * route; another screen would simply be another file alongside it.
 *
 * Parameters are passed through the query string (?id=…), which also works in
 * the single-file export after the hash: #/p/example/detail?id=A-2481
 */

import { Link, useSearchParams } from 'react-router'

import { DsButton } from '../../components'
import { auftragById, statusFarbe } from './_shared/data'
import { Shell } from './_shared/Shell'

export default function Detail() {
  const [params] = useSearchParams()
  const auftrag = auftragById(params.get('id'))

  if (!auftrag) {
    return (
      <Shell titel="Work order" zurueck={{ to: '/p/example', label: 'Work orders' }}>
        <p className="text-base text-ink">This work order does not exist.</p>
        <p className="mt-3 text-sm text-ink-muted">
          Empty state: considered explicitly, not omitted.
        </p>
        <Link to="/p/example" className="mt-6 inline-block">
          <DsButton variant="secondary">Back to list</DsButton>
        </Link>
      </Shell>
    )
  }

  return (
    <Shell titel={auftrag.titel} zurueck={{ to: '/p/example', label: 'Work orders' }}>
      <div className="flex flex-wrap items-center gap-4">
        <span className="font-mono text-sm text-ink-muted">{auftrag.id}</span>
        <span
          className={`rounded-full px-3 py-1 text-xs font-medium ${statusFarbe[auftrag.status]}`}
        >
          {auftrag.status}
        </span>
      </div>

      <dl className="mt-6 grid gap-4 sm:grid-cols-2">
        <div>
          <dt className="text-xs text-ink-muted">Customer</dt>
          <dd className="mt-1 text-base text-ink">{auftrag.kunde}</dd>
        </div>
        <div>
          <dt className="text-xs text-ink-muted">Service location</dt>
          <dd className="mt-1 text-base text-ink">{auftrag.ort}</dd>
        </div>
        <div>
          <dt className="text-xs text-ink-muted">Due</dt>
          <dd className="mt-1 text-base text-ink">{auftrag.faellig}</dd>
        </div>
      </dl>

      <p className="mt-6 max-w-2xl text-base text-ink">{auftrag.beschreibung}</p>

      <h2 className="mt-8 text-lg font-medium text-ink">Line items</h2>
      <ul className="mt-4 divide-y divide-line rounded-lg border border-line">
        {auftrag.positionen.map((position) => (
          <li key={position.bezeichnung} className="flex justify-between gap-4 p-4">
            <span className="text-base text-ink">{position.bezeichnung}</span>
            <span className="font-mono text-sm text-ink-muted">{position.menge}×</span>
          </li>
        ))}
      </ul>

      <div className="mt-8 flex flex-wrap gap-3">
        <DsButton>Complete</DsButton>
        <DsButton variant="secondary">Reschedule</DsButton>
        <DsButton variant="ghost" size="sm">
          View service report
        </DsButton>
      </div>
    </Shell>
  )
}
